export const listIdToTag = {
    "3d": "3D",
    "adult": "Adult",
    "animal-girl": "Animal girl",
    "artist": "Artist",
    "bao-dam": "Bạo Dâm",
    "cg": "CG",
    "choi-hai-lo": "Chơi Hai Lỗ",
    "complete": "Complete",
    "con-trung": "Côn Trùng",
    "cosplay": "Cosplay",
    "doujinshi": "Doujinshi",
    "do-boi": "Đồ Bơi",
    "elf": "Elf",
    "fantasy": "Fantasy",
    "furry": "Furry",
    "futanari": "Futanari",
    "gangbang": "Gangbang",
    "gender-bender": "Gender Bender",
    "giao-vien": "Giáo Viên",
    "group": "Group",
    "guro": "Guro",
    "hai-huoc": "Hài Hước",
    "ham-hiep": "Hãm Hiếp",
    "harem": "Harem",
    "hau-gai": "Hầu Gái",
    "hau-mon": "Hậu Môn",
    "housewife": "Housewife",
    "kinh-di": "Kinh Dị",
    "kogal": "Kogal",
    "lang-man": "Lãng Mạn",
    "lao-gia-dam": "Lão Gìa Dâm",
    "loan-luan": "Loạn Luân",
    "loli": "Loli",
    "lxhentai": "LXHENTAI",
    "mang-thai": "Mang Thai",
    "manhwa": "Manhwa",
    "mat-kinh": "Mắt Kính",
    "mature": "Mature",
    "milf": "Milf",
    "mind-break": "Mind Break",
    "mind-control": "Mind Control",
    "monster-girl": "Monster Girl",
    "nguc-lon": "Ngực Lớn",
    "nguc-nho": "Ngực Nhỏ",
    "no-le": "Nô Lệ",
    "ntr": "NTR",
    "nu-sinh": "Nữ Sinh",
    "oneshot": "OneShot",
    "quai-vat": "Quái Vật",
    "scat": "Scat",
    "series": "Series",
    "shota": "Shota",
    "supernatural": "Supernatural",
    "the-thao": "Thể Thao",
    "thu-vat": "Thú Vật",
    "trap": "Trap",
    "truyen-comic": "Truyện Comic",
    "truyen-khong-che": "Truyện Không Che",
    "truyen-mau": "Truyện Màu",
    "truyen-ngan": "Truyện Ngắn",
    "virgin": "Virgin",
    "xuc-tua": "Xúc Tua",
    "y-ta": "Y Tá",
    "yaoi": "Yaoi",
    "yuri": "Yuri",
};

export const listTagToId = {
    "3D": "3d",
    "Action": "action",
    "Adult": "adult",
    "Adventure": "adventure",
    "Ahegao": "ahegao",
    "Angel": "angel",
    "Animal girl": "animal-girl",
    "Artist": "artist",
    "Big Penis": "big-penis",
    "Body Swap": "body-swap",
    "Brocon": "brocon",
    "Brother": "brother",
    "business-suit": "Business Suit",
    "Bạo Dâm": "bao-dam",
    "CG": "cg",
    "Che nhiều": "che-nhieu",
    "Che ít": "che-it",
    "Chơi Hai Lỗ": "choi-hai-lo",
    "Complete": "complete",
    "Condom": "condom",
    "Cosplay": "cosplay",
    "Cousin": "cousin",
    "Crotch Tattoo": "crotch-tattoo",
    "Có che": "co-che",
    "Côn Trùng": "con-trung",
    "Dark Skin": "dark-skin",
    "DemonGirl": "demongirl",
    "Dirty Old Man": "dirty-old-man",
    "DogGirl": "doggirl",
    "Doujinshi": "doujinshi",
    "Drama": "drama",
    "Ecchi": "ecchi",
    "Elder Sister": "elder-sister",
    "Elf": "elf",
    "Fantasy": "fantasy",
    "Father": "father",
    "Furry": "furry",
    "Futanari": "futanari",
    "Gangbang": "gangbang",
    "Gender Bender": "gender-bender",
    "Giáo Viên": "giao-vien",
    "Group": "group",
    "Guro": "guro",
    "Hairy": "hairy",
    "Harem": "harem",
    "HENTAIVN": "hentaivn",
    "Historical": "historical",
    "Housewife": "housewife",
    "Hài Hước": "hai-huoc",
    "Hãm Hiếp": "ham-hiep",
    "Hầu Gái": "hau-gai",
    "Hậu Môn": "hau-mon",
    "Idol": "idol",
    "Invisible": "invisible",
    "Isekai": "isekai",
    "Không Che": "truyen-khong-che",
    "Kinh Dị": "kinh-di",
    "Kogal": "kogal",
    "Loli": "loli",
    "Loạn Luân": "loan-luan",
    "LXHENTAI": "lxhentai",
    "Lãng Mạn": "lang-man",
    "Lão Gìa Dâm": "lao-gia-dam",
    "Maids": "maids",
    "Mang Thai": "mang-thai",
    "Manhua": "manhua",
    "Manhwa": "manhwa",
    "Masturbation": "masturbation",
    "Mature": "mature",
    "Miko": "miko",
    "Milf": "milf",
    "Mind Break": "mind-break",
    "Mind Control": "mind-control",
    "Monster Girl": "monster-girl",
    "Mother": "mother",
    "Mông to": "mong-to",
    "Mắt Kính": "mat-kinh",
    "Netori": "netori",
    "Ngực Lớn": "nguc-lon",
    "Ngực Nhỏ": "nguc-nho",
    "NTR": "ntr",
    "Nun": "ni-co",
    "Nách": "nach",
    "Nô Lệ": "no-le",
    "Nữ Sinh": "nu-sinh",
    "OneShot": "oneshot",
    "Pantyhose": "pantyhose",
    "Pregnant": "pregnant",
    "Prostitution": "prostitution",
    "Quái Vật": "quai-vat",
    "Romance": "romance",
    "Scat": "scat",
    "School Uniform": "school-uniform",
    "SchoolGirl": "schoolgirl",
    "Series": "series",
    "Sex Toys": "sex-toys",
    "Short Hentai": "short-hentai",
    "Shota": "shota",
    "Shoujo": "shoujo",
    "Siscon": "siscon",
    "Sister": "sister",
    "Small Boobs": "nguc-nho",
    "Son": "son",
    "Sports": "sports",
    "Stockings": "stockings",
    "Supernatural": "supernatural",
    "Sweating": "sweating",
    "Swimsuit": "swimsuit",
    "Teacher": "teacher",
    "Thú Vật": "thu-vat",
    "Thể Thao": "the-thao",
    "Thổi kèn": "thoi-ken",
    "Time Stop": "time-stop",
    "Trap": "trap",
    "Truyện Comic": "truyen-comic",
    "Truyện Màu": "truyen-mau",
    "Truyện Ngắn": "truyen-ngan",
    "Truyện Việt": "truyen-viet",
    "Trò chơi": "tro-choi",
    "Tsundere": "tsundere",
    "Tạp dề": "tap-de",
    "Tống tiền": "tong-tien",
    "Virgin": "virgin",
    "Webtoon": "webtoon",
    "Xúc Tua": "xuc-tua",
    "Y Tá": "y-ta",
    "Yandere": "yandere",
    "Yaoi": "yaoi",
    "Yuri": "yuri",
    "Zombie": "zombie",
    "Đồ Bơi": "do-boi"
}


// Hentaivn
export const listTagToIdHentaivn = {
    "HENTAIVN": "hentaivn",
    "Action": "action",
    "Adventure": "adventure",
    "Ahegao": "ahegao",
    "Angel": "angel",
    "Tạp dề": "tap-de",
    "Nách": "nach",
    "Trò chơi": "tro-choi",
    "Mông to": "mong-to",
    "Big Penis": "big-penis",
    "Tống tiền": "tong-tien",
    "Thổi kèn": "thoi-ken",
    "Body Swap": "body-swap",
    "Brocon": "brocon",
    "Brother": "brother",
    "business-suit": "Business Suit",
    "Che ít": "che-it",
    "Che nhiều": "che-nhieu",
    "Có che": "co-che",
    "Condom": "condom",
    "Cousin": "cousin",
    "Crotch Tattoo": "crotch-tattoo",
    "Dark Skin": "dark-skin",
    "DemonGirl": "demongirl",
    "Dirty Old Man": "dirty-old-man",
    "DogGirl": "doggirl",
    "Drama": "drama",
    "Ecchi": "ecchi",
    "Elder Sister": "elder-sister",
    "Father": "father",
    "Hairy": "hairy",
    "Historical": "historical",
    "Idol": "idol",
    "Invisible": "invisible",
    "Isekai": "isekai",
    "Maids": "maids",
    "Manhua": "manhua",
    "Masturbation": "masturbation",
    "Miko": "miko",
    "Mother": "mother",
    "Netori": "netori",
    "Nun": "ni-co",
    "Pantyhose": "pantyhose",
    "Pregnant": "pregnant",
    "Prostitution": "prostitution",
    "Romance": "romance",
    "School Uniform": "school-uniform",
    "SchoolGirl": "schoolgirl",
    "Sex Toys": "sex-toys",
    "Short Hentai": "short-hentai",
    "Shoujo": "shoujo",
    "Siscon": "siscon",
    "Sister": "sister",
    "Slave": "slave",
    "Small Boobs": "small-boobs",
    "Son": "son",
    "Sports": "sports",
    "Stockings": "stockings",
    "Sweating": "sweating",
    "Swimsuit": "swimsuit",
    "Teacher": "teacher",
    "Time Stop": "time-stop",
    "Truyện Việt": "truyen-viet",
    "Tsundere": "tsundere",
    "Webtoon": "webtoon",
    "Yandere": "yandere",
    "Zombie": "zombie"
}

export const listIdToTagHentaivn = {
    "hentaivn": "HENTAIVN",
    "action": "Action",
    "adventure": "Adventure",
    "ahegao": "Ahegao",
    "angel": "Angel",
    "tap-de": "Tạp dề",
    "nach": "Nách",
    "tro-choi": "Trò chơi",
    "mong-to": "Mông to",
    "big-penis": "Big Penis",
    "tong-tien": "Tống tiền",
    "thoi-ken": "Thổi kèn",
    "body-swap": "Body Swap",
    "brocon": "Brocon",
    "brother": "Brother",
    "Business Suit": "business-suit",
    "che-it": "Che ít",
    "che-nhieu": "Che nhiều",
    "co-che": "Có che",
    "condom": "Condom",
    "cousin": "Cousin",
    "crotch-tattoo": "Crotch Tattoo",
    "dark-skin": "Dark Skin",
    "demongirl": "DemonGirl",
    "dirty-old-man": "Dirty Old Man",
    "doggirl": "DogGirl",
    "drama": "Drama",
    "ecchi": "Ecchi",
    "elder-sister": "Elder Sister",
    "father": "Father",
    "hairy": "Hairy",
    "historical": "Historical",
    "idol": "Idol",
    "invisible": "Invisible",
    "isekai": "Isekai",
    "maids": "Maids",
    "manhua": "Manhua",
    "masturbation": "Masturbation",
    "miko": "Miko",
    "mother": "Mother",
    "netori": "Netori",
    "ni-co": "Nun",
    "pantyhose": "Pantyhose",
    "pregnant": "Pregnant",
    "prostitution": "Prostitution",
    "romance": "Romance",
    "school-uniform": "School Uniform",
    "schoolgirl": "SchoolGirl",
    "sex-toys": "Sex Toys",
    "short-hentai": "Short Hentai",
    "shoujo": "Shoujo",
    "siscon": "Siscon",
    "sister": "Sister",
    "slave": "Slave",
    "small-boobs": "Small Boobs",
    "son": "Son",
    "sports": "Sports",
    "stockings": "Stockings",
    "sweating": "Sweating",
    "swimsuit": "Swimsuit",
    "teacher": "Teacher",
    "time-stop": "Time Stop",
    "truyen-viet": "Truyện Việt",
    "tsundere": "Tsundere",
    "webtoon": "Webtoon",
    "yandere": "Yandere",
    "zombie": "Zombie"
}

// export const listTag = [
//     {   
//         id: "",
//         name: "",
//         isGreatBook: false,
//     },
//     {   
//         id: "",
//         name: "",
//         isGreatBook: false,
//     },
// ]