export const listIdToTag = {
    "3d": "3D",
    "adult": "Adult",
    "animal-girl": "Animal girl",
    "artist": "Artist",
    "bao-dam": "Bạo Dâm",
    "cg": "CG",
    "choi-hai-lo": "Chơi Hai Lỗ",
    "complete": "Complete",
    "con-trung": "Côn Trùng",
    "cosplay": "Cosplay",
    "doujinshi": "Doujinshi",
    "do-boi": "Đồ Bơi",
    "elf": "Elf",
    "fantasy": "Fantasy",
    "furry": "Furry",
    "futanari": "Futanari",
    "gangbang": "Gangbang",
    "gender-bender": "Gender Bender",
    "giao-vien": "Giáo Viên",
    "group": "Group",
    "guro": "Guro",
    "hai-huoc": "Hài Hước",
    "ham-hiep": "Hãm Hiếp",
    "harem": "Harem",
    "hau-gai": "Hầu Gái",
    "hau-mon": "Hậu Môn",
    "housewife": "Housewife",
    "kinh-di": "Kinh Dị",
    "kogal": "Kogal",
    "lang-man": "Lãng Mạn",
    "lao-gia-dam": "Lão Gìa Dâm",
    "loan-luan": "Loạn Luân",
    "loli": "Loli",
    "lxhentai": "LXHENTAI",
    "mang-thai": "Mang Thai",
    "manhwa": "Manhwa",
    "mat-kinh": "Mắt Kính",
    "mature": "Mature",
    "milf": "Milf",
    "mind-break": "Mind Break",
    "mind-control": "Mind Control",
    "monster-girl": "Monster Girl",
    "nguc-lon": "Ngực Lớn",
    "nguc-nho": "Ngực Nhỏ",
    "no-le": "Nô Lệ",
    "ntr": "NTR",
    "nu-sinh": "Nữ Sinh",
    "oneshot": "OneShot",
    "quai-vat": "Quái Vật",
    "scat": "Scat",
    "series": "Series",
    "shota": "Shota",
    "supernatural": "Supernatural",
    "the-thao": "Thể Thao",
    "thu-vat": "Thú Vật",
    "trap": "Trap",
    "truyen-comic": "Truyện Comic",
    "truyen-khong-che": "Truyện Không Che",
    "truyen-mau": "Truyện Màu",
    "truyen-ngan": "Truyện Ngắn",
    "virgin": "Virgin",
    "xuc-tua": "Xúc Tua",
    "y-ta": "Y Tá",
    "yaoi": "Yaoi",
    "yuri": "Yuri",
};

export const listTagToId = {
    "3D": "3d",
    "Adult": "adult",
    "Animal girl": "animal-girl",
    "Artist": "artist",
    "Bạo Dâm": "bao-dam",
    "CG": "cg",
    "Chơi Hai Lỗ": "choi-hai-lo",
    "Complete": "complete",
    "Côn Trùng": "con-trung",
    "Cosplay": "cosplay",
    "Doujinshi": "doujinshi",
    "Đồ Bơi": "do-boi",
    "Elf": "elf",
    "Fantasy": "fantasy",
    "Furry": "furry",
    "Futanari": "futanari",
    "Gangbang": "gangbang",
    "Gender Bender": "gender-bender",
    "Giáo Viên": "giao-vien",
    "Group": "group",
    "Guro": "guro",
    "Hài Hước": "hai-huoc",
    "Hãm Hiếp": "ham-hiep",
    "Harem": "harem",
    "Hầu Gái": "hau-gai",
    "Hậu Môn": "hau-mon",
    "Housewife": "housewife",
    "Kinh Dị": "kinh-di",
    "Kogal": "kogal",
    "Lãng Mạn": "lang-man",
    "Lão Gìa Dâm": "lao-gia-dam",
    "Loạn Luân": "loan-luan",
    "Loli": "loli",
    "LXHENTAI": "lxhentai",
    "Mang Thai": "mang-thai",
    "Manhwa": "manhwa",
    "Mắt Kính": "mat-kinh",
    "Mature": "mature",
    "Milf": "milf",
    "Mind Break": "mind-break",
    "Mind Control": "mind-control",
    "Monster Girl": "monster-girl",
    "Ngực Lớn": "nguc-lon",
    "Ngực Nhỏ": "nguc-nho",
    "Nô Lệ": "no-le",
    "NTR": "ntr",
    "Nữ Sinh": "nu-sinh",
    "OneShot": "oneshot",
    "Quái Vật": "quai-vat",
    "Scat": "scat",
    "Series": "series",
    "Shota": "shota",
    "Supernatural": "supernatural",
    "Thể Thao": "the-thao",
    "Thú Vật": "thu-vat",
    "Trap": "trap",
    "Truyện Comic": "truyen-comic",
    "Truyện Không Che": "truyen-khong-che",
    "Truyện Màu": "truyen-mau",
    "Truyện Ngắn": "truyen-ngan",
    "Virgin": "virgin",
    "Xúc Tua": "xuc-tua",
    "Y Tá": "y-ta",
    "Yaoi": "yaoi",
    "Yuri": "yuri",
};
